### PR TITLE
NAS-123279 / 24.04 / Ignore errors due to sharesmb/sharenfs on pool import

### PR DESCRIPTION
**Pull request by usaleem-ix**
### Motivation and Context
For users who have `sharesmb/sharenfs` property set to `on`, when they try to import the 
pool on TrueNAS, they run into error and pool import fails.

### Description
For `zpool import` and `zpool split`, `zpool_enable_datasets` is called to mount and share
all datasets in a pool. If there is an error while mounting or sharing any dataset in the pool,
the status of import or split is reported as failure. However, the changes do show up in
zpool list.

This PR updates the error reporting in zpool import and zpool split path. More
descriptive messages are shown to user in case there is an error during mount or
share. Errors in mount or share do not effect the overall status of `zpool import` and
`zpool split`.

`zfs-share.service` executes `zfs share -a` on every boot to share any filesystems with
sharesmb/sharenfs properties enabled. This PR also disables this service.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by amotin — COMMENTED** [review]
Same as I written in private, I have no objections against this if we are consciously using different path.  It is obviously not unstreamable in such way, unless we make it configurable somehow, via module parameter, environment variable (would be weird) or something else.  But since on TrueNAS we never used this mechanism, relying on middleware and WebUI to set up shared, I am not sure we really want it.  I'd ask @anodos325 about it.

**Comment by amotin** [comment]
> Maybe what we should do is to disable this property if it is enabled on import (just a thought).

I think we should check error reporting during pool import.  If  pool is imported enough to be seen in `zpool list`, it is not a failure, and middleware should be able to detect it as such.  Some mount, export, etc errors should be reported by `zpool import` somehow and may be reported in UI, but they should not be fatal as soon as pool is imported at all.

**Comment by usaleem-ix** [comment]
On a quick glance, I see that `zpool import` reports failure, even though the pool shows up in zpool list.

```
# pool is not present before
root@truenas[~]# ls /mnt/
tank
root@truenas[~]# zpool list
NAME        SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
boot-pool    14G  2.61G  11.4G        -         -     0%    18%  1.00x    ONLINE  -
tank         25G  6.14M  25.0G        -         -     0%     0%  1.00x    ONLINE  /mnt

# SMB share creation fails
root@truenas[~]# zpool import xpool
cannot share 'xpool/ds: system error': SMB share creation failed

# zpool import reports failure
root@truenas[~]# echo $?
1

# pool shows up
root@truenas[~]# zpool list
NAME        SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
boot-pool    14G  2.61G  11.4G        -         -     0%    18%  1.00x    ONLINE  -
tank         25G  6.46M  25.0G        -         -     0%     0%  1.00x    ONLINE  /mnt
xpool      7.50G   219K  7.50G        -         -     0%     0%  1.00x    ONLINE  -

# mounted under /mnt/
root@truenas[~]# ls /mnt/
tank  xpool
```

When the system comes back up after I reboot, I cannot see the pool anymore:
```
root@truenas[~]# zpool list
NAME        SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
boot-pool    14G  2.61G  11.4G        -         -     0%    18%  1.00x    ONLINE  -
tank         25G  6.14M  25.0G        -         -     0%     0%  1.00x    ONLINE  /mnt
```
I will try to see where the error is returned in code.

**Comment by usaleem-ix** [comment]
In libzfs, when we import the pool from `do_import`,  it calls `zpool_enable_datasets` to mount and then share all datasets within the given pool. `zpool_enable_datasets` calls `zfs_share_one` which in turn calls `zfs_share` for all filesystems. `zfs_share` is the higher level function in libzfs that uses libshare to share the filesystem.

For `sharesmb` case, we do not return the error now. Instead, the error message is printed and pool import is allowed to continue.

I have tested this patch and I was able to successfully import a pool created on Debian with sharesmb set to `on` for one of the datasets. Pool import succeeds from the UI and pool was present after multiple reboots. Pool export also works without issue. After exporting the pool from UI, importing the pool from command line also reports success.

```
root@truenas[~]# zpool list
NAME        SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
boot-pool    14G  2.34G  11.7G        -         -     0%    16%  1.00x    ONLINE  -

root@truenas[~]# zpool import xpool 
cannot share 'xpool/ds: system error': SMB share creation failed

root@truenas[~]# echo $?
0

root@truenas[~]# zpool list
NAME        SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
boot-pool    14G  2.33G  11.7G        -         -     0%    16%  1.00x    ONLINE  -
xpool      15.5G   302K  15.5G        -         -     0%     0%  1.00x    ONLINE  -

```

**Review by amotin — APPROVED** [review]

**Pull request closed without merging**
