### PR TITLE
NAS-116639 / Add native Debian Packaging for ZFS

### PR DESCRIPTION
**Pull request by usaleem-ix**
### Motivation and Context
The existing Debian packages for packages are converted from RPM, which
do not provide separate dbgsym packages.

### Description
This PR adds support for native Debian packaging for ZFS. `make` targets for
building native packages have also been added.

Along with native packaging updates, this PR contains couple of updates aside
from packaging to get everything working.

These updates include:

- GitHub CI now builds native packages to exercise ZTS.
- Ubuntu 18.04 test runners are removed and Ubuntu 22.04 added.
- Bash_completion script installation was broken in TrueNAS ZFS, which is now fixed in RPM packages and native packages. Upstream does not have this issue as they have updated the make build process and it is fixed in there.
- Python distutils are replaced with sysconfig; distutils will be deprecated soon.
- GitHub CI's Skip duplicate actions version is updated to latest. Node.js 12 actions will be deprecated soon.
- `Provides:` field have been added to packages so that native packages can still be looked up with old names for scale-build. Otherwise we would have to update the `Depends:` section of all the packages that depend on OpenZFS with new package names.
- The change-log present in contrib/truenas has been copied to contrib/debian.

### How Has This Been Tested?
ZTS runs on GitHub CI and TrueNAS SCALE

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by freqlabs — CHANGES_REQUESTED** [review]
Awesome work! Let's remove the contrib/truenas/ directory with this, too.

**Comment by usaleem-ix** [comment]
> Awesome work! Let's remove the contrib/truenas/ directory with this, too.

Thank you. I was thinking maybe keep that for now, in case if a regression is found and it's not trivial, we can just revert the scale-build PR only so production continues to build?

**Comment by freqlabs** [comment]
Actually maybe we want to keep that to make it easier merging back to bluefin. All the old packaging works I guess, since the build-deb workflow passed. The workflow should be updated to test the new packaging though.

**Comment by usaleem-ix** [comment]
> Actually maybe we want to keep that to make it easier merging back to bluefin. All the old packaging still seems to work, since the build-deb workflow passed. The workflow should be updated to test the new packaging though.

Sure, I'll update the build-deb workflow to use native packaging.

**Comment by usaleem-ix** [comment]
I have added a build-native-deb workflow to build native Debian packages. Services will remain disabled when packages are installed.

**Review by freqlabs — APPROVED** [review]

**Comment by usaleem-ix** [comment]
The signed off signature was missing from last commit log.

**Pull request merged**
